name: Bump, tag and publish to npm

on:
  push:
    branches:
      - 'master'

jobs:
  bump-version:
    uses: snapshot-labs/actions/.github/workflows/bump-version.yml@inject-dotenv-content
    secrets: inherit

  create-github-release:
    uses: snapshot-labs/actions/.github/workflows/create-github-release.yml@add-create-release-workflow
    needs: bump-version
    secrets: inherit

  publish-npm:
    uses: snapshot-labs/actions/.github/workflows/publish-npm.yml@main
    secrets: inherit
    needs: [bump-version, create-github-release]
