name: Bump, tag and publish to npm

on:
  push:
    branches:
      - 'master'

jobs:
  bump-version:
    uses: snapshot-labs/actions/.github/workflows/bump-version.yml@inject-dotenv-content
    secrets: inherit

  echo-newtag:
    needs: bump-version
    runs-on: ubuntu-latest
    name: output

    steps:
      - name: echo
        run: echo ${{ toJSON(needs.bump-version.version-bump) }}
      - name: echo2
        run: echo "$GITHUB_CONTEXT"


  # create-github-release:
  #   uses: snapshot-labs/actions/.github/workflows/create-github-release.yml@add-create-release-workflow
  #   needs: bump-version
  #   secrets: inherit
  #   with:
  #     tag_name: ${{ needs.bump-version.outputs.newTag }}

  # publish-npm:
  #   uses: snapshot-labs/actions/.github/workflows/publish-npm.yml@main
  #   secrets: inherit
  #   needs: [bump-version, create-github-release]
