name: Create Github release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-github-release:
    name: Create a Github release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
